export const datos = 
    [
                {
                "id": 1,
                "nombre": "China",
                "edad_aprox": "casi dos años",
                "tamaño": "mediano",
                "tipo": "gato",
                "raza": "cruza",
                "genero": "H",
                "vacunas": "TODAS",
                "castrado": false,
                "visita_vete": "10-22-2022",
                "tratamiento": "ninguno",
                "actividades": ["romper cartón", "domar de sillónes"],
                "cualidades": ["agil"],
                "discapacidad": "NINGUNA",
                "pelaje": "largo",
                "caracter": ["amigable"],
                "enfermedades": "NINGUNA",
                "comida": ["iams", "pescado"],
                "img": "https://cdn.pixabay.com/photo/2015/04/23/21/59/tree-736877_960_720.jpg",
                "adoptado": false
                },
                {
                "id": 2,
                "nombre": "Pipo",
                "edad_aprox": "12 años",
                "tamaño": "mediano",
                "tipo": "perro",
                "raza": "mestizo",
                "genero": "M",
                "vacunas": "TODAS",
                "castrado": true,
                "visita_vete": "si",
                "tratamiento": "ninguno",
                "actividades": ["estar tirado"],
                "cualidades": ["patas marrones", "pecho blanco"],
                "discapacidad": "NINGUNA",
                "pelaje": "corto",
                "caracter": ["vago"],
                "enfermedades": "NINGUNA",
                "comida": ["Pedigree", "lo que haya en la mesa"],
                "img": "https://www.investigacionyciencia.es/images/21536/articleImage-minimal.jpg",
                "adoptado": false
                },
                {
                "id": 3,
                "nombre": "Mia",
                "edad_aprox": "3 años",
                "tamaño": "pequeño",
                "tipo": "gata",
                "raza": "comun",
                "genero": "H",
                "vacunas": "todas",
                "castrado": false,
                "visita_vete": "trimestral",
                "tratamiento": "gotasdiar",
                "actividades": ["jugar todo el dia"],
                "cualidades": ["cariñosa"],
                "discapacidad": "visual",
                "caracter": ["no"],
                "comida": ["vitalcat"],
                "img": "https://cf.ltkcdn.net/gatos/images/std/236641-800x515r1-etapas-desarrollo-gatitos.jpg",
                "adoptado": false
                },
                {
                "id": 4,
                "nombre": "sting",
                "edad_aprox": "6 años",
                "tamaño": "grande",
                "tipo": "perro",
                "raza": "labrador",
                "genero": "M",
                "vacunas": "todas",
                "castrado": false,
                "visita_vete": "10-22-2022",
                "tratamiento": "ninguno",
                "actividades": ["dormir"],
                "cualidades": ["es bueno con los niños"],
                "discapacidad": "largo",
                "pelaje": "false",
                "caracter": ["jugueton"],
                "enfermedades": "NINGUNA",
                "comida": ["excellent"],
                "img": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTd71iHlDpYxdGcZpQwFL_5XcXlkgmzpcG5Zg&usqp=CAU",
                "adoptado": false
                },
                {
                "id": 5,
                "nombre": "Dexter",
                "edad_aprox": "dos años",
                "tamaño": "mediano",
                "tipo": "gato",
                "raza": "cruza",
                "genero": "H",
                "vacunas": "todas",
                "castrado": true,
                "visita_vete": "10-22-2022",
                "tratamiento": "ninguno",
                "actividades": ["correr", "jugar con otros perros"],
                "cualidades": ["mimoso"],
                "discapacidad": "NINGUNA",
                "pelaje": "corto",
                "caracter": ["temperamental"],
                "enfermedades": "NINGUNA",
                "comida": ["Nutrique"],
                "img": "https://cdn.pixabay.com/photo/2016/11/29/11/26/dog-1869167_960_720.jpg",
                "adoptado": false
                },
                {
                "id": 6,
                "nombre": "Peperina",
                "edad_aprox": "6 meses",
                "tamaño": "chico",
                "tipo": "perro",
                "raza": "MIXTA",
                "genero": "H",
                "vacunas": "TODAS",
                "castrado": false,
                "visita_vete": "10-22-2022",
                "tratamiento": "ninguno",
                "actividades": ["perseguir mi cola", "ladrarle a los pájaros"],
                "cualidades": ["juguetona, cariñosa"],
                "discapacidad": "NINGUNA",
                "caracter": ["Tímida"],
                "enfermedades": "NINGUNA",
                "comida": ["Carne cruda"],
                "img": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRIYUG094cHATHHkVDdt2YEJ0HlaXyesxd4tw&usqp=CAU",
                "adoptado": false
                },
                {
                "id": 7,
                "nombre": "Gala",
                "edad_aprox": "4 años",
                "tamaño": "mediano",
                "tipo": "perro",
                "raza": "galgo",
                "genero": "H",
                "vacunas": "TODAS",
                "castrado": false,
                "visita_vete": "03-08-2022",
                "tratamiento": "no",
                "actividades": ["comer", "salir a pasear", "dormir"],
                "cualidades": ["corre rápido", "salta en dos patas"],
                "discapacidad": "no",
                "caracter": ["amigable"],
                "enfermedades": "NINGUNA",
                "comida": ["Comida balanceada", "carne", "arroz", "verduras"],
                "img": "https://www.tiendanimal.es/articulos/wp-content/uploads/2020/03/galgo.jpg",
                "adoptado": false
                },
                {
                "id": 8,
                "nombre": "Simba",
                "edad_aprox": "Un año",
                "tamaño": "mediano",
                "tipo": "Gato",
                "raza": "Cruza",
                "genero": "H",
                "vacunas": "2",
                "castrado": false,
                "visita_vete": "03-06-2022",
                "tratamiento": "no",
                "actividades": ["cazar", "estar rodeado de gente"],
                "cualidades": ["trepador"],
                "discapacidad": "NINGUNA",
                "pelaje": "Corto",
                "caracter": ["mimoso"],
                "enfermedades": "no",
                "comida": ["purina", "pollo"],
                "img": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS9QdFTt8rlWCHUpitPmibeA088Ngx5EJ10og&usqp=CAU",
                "adoptado": false
                },
                {
                "id": 9,
                "nombre": "Pepina",
                "edad_aprox": "3 meses",
                "tamaño": "pequeño",
                "tipo": "Gato",
                "raza": "Cruza",
                "genero": "H",
                "vacunas": "No se sabe",
                "castrado": false,
                "visita_vete": "-",
                "tratamiento": "ninguno",
                "actividades": ["dormir", "jugar con el pompóm", "rasguñar muebles"],
                "cualidades": ["Trepadora"],
                "discapacidad": "Ninguna",
                "pelaje": "Largo",
                "caracter": ["Amigable"],
                "enfermedades": "Ninguna",
                "comida": ["leche", "pollo"],
                "img": "https://www.purina.es/sites/default/files/styles/ttt_image_510/public/2021-12/EL%20PRIMER%20D%C3%8DA%20DE%20UN%20GATO%20NUEVO%20EN%20CASA-1.jpg?itok=peJkgf-V",
                "adoptado": false
                },
                {
                "id": 10,
                "nombre": "rex",
                "edad_aprox": "2 años",
                "tamaño": "Grande",
                "tipo": "Perro",
                "raza": "Pastor Aleman",
                "genero": "M",
                "vacunas": "TODAS",
                "castrado": false,
                "visita_vete": "5-12-2022",
                "tratamiento": "ninguno",
                "actividades": ["buscar cosas", "correr"],
                "cualidades": ["buen olfato", "inteligente"],
                "discapacidad": "NINGUNA",
                "pelaje": "corto",
                "caracter": ["amigable"],
                "enfermedades": "NINGUNA",
                "comida": ["perrarina", "carne"],
                "img": "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F47%2F2021%2F08%2F23%2Fpictures-of-german-shepherds-2000.jpg",
                "adoptado": true
                }                
            ]